### ISSUE TITLE
[Web admin]【管理者登録】連続で管理者登録（都道府県管理者）をすると都道府県の選択プルダウンが増えていく

### ISSUE THREAD

**Issue by KayokoYamashita** [mamori-i-japan/mamori-i-japan-admin-panel#127]
- バグ詳細 Bug Details 
　連続して都道府県管理者を登録すると都道府県選択のプルダウンが増えてしまう。
　複数、登録した場合は末尾の都道府県が登録される。

- テスト実施環境 Implementation environment 
　MAC/Chrome

- 期待値 Expected value 
　都道府県選択のプルダウンは1つだけ表示される

![スクリーンショット 2020-05-13 16 54 33](https://user-images.githubusercontent.com/36686492/81787267-bc1f5300-953b-11ea-95c8-326c5a4fe0e4.png)
![maxtest3-3](https://user-images.githubusercontent.com/36686492/81787457-086a9300-953c-11ea-8e57-05d9fb0d87b7.jpg)

**Comment by zhumeisongsong** [comment]
Fixed in #126
