### ISSUE TITLE
[Web admin]【管理者登録】通信断のときのエラー表示が正しい？（想定しているものかどうか）

### ISSUE THREAD

**Issue by KayokoYamashita** [mamori-i-japan/mamori-i-japan-admin-panel#128]
- バグ詳細 Bug Details 
　XXX, 不明なエラーが発生しました。

- テスト実施環境 Implementation environment 
　Win/Edge

- 期待値 Expected value 
　期待結果が正しいか不明で判断できない。

- バグ再現手順 Reproduction method 
1. ログインする
2. 左メニュー「管理者一覧」をクリックする
3. 「追加」ボタンをクリックする
4. 任意のメールアドレスを入力する
5. Wi-Fi接続を切る
6. 保存ボタンをクリックする

MAC/Chrome
![スクリーンショット 2020-05-13 16 31 19](https://user-images.githubusercontent.com/36686492/81784089-50d38200-9537-11ea-8635-11eb3c1d66ca.png)

Win/Edge
![通信断-2](https://user-images.githubusercontent.com/36686492/81784231-824c4d80-9537-11ea-9cf2-20fbca2466a1.jpg)

**Comment by zhumeisongsong** [comment]
#153 対応完了しました。
