### ISSUE TITLE
[Web admin]【ログイン】メール本文の改行位置がおかしい

### ISSUE THREAD

**Issue by KayokoYamashita** [mamori-i-japan/mamori-i-japan-admin-panel#131]
□のところで改行してほしい。

// ==========
お客様

このメールアドレスでの contact-tracing-stg へのログインのリクエストを受け付けました。□hogehoge@monstar-lab.com のアカウントでログインするには、こちらのリンクをクリックしてください。

contact-tracing-stg にログイン

このリンクをリクエストしていない場合は、このメールを無視してください。

よろしくお願いいたします。

contact-tracing-stg チーム

========= //

**Comment by ebiryu** [comment]
こちらのバグは対応できないのでCloseします。
（理由：Firebaseが用意するテンプレートを修正できないため。修正する場合は認証を根本から作り直す必要あり。）

https://stackoverflow.com/questions/51334804/change-the-email-template-when-using-firebase-email-link-authentication
