### ISSUE TITLE
[Web admin]【都道府県お知らせ一覧】のURLに全角文字が入力できてしまう

### ISSUE THREAD

**Issue by KayokoYamashita** [mamori-i-japan/mamori-i-japan-admin-panel#138]
- バグ詳細 Bug Details 
　− URLに全角文字、URLでない文字列が登録できてしまう。

- テスト実施環境 Implementation environment 
　− stg環境

- 期待値 Expected value 
　− 半角英数でURLのものを登録できること。

- バグ再現手順 Reproduction method 
　1. 都道府県お知らせ一覧で編集ボタンをクリックする
　2. URL に全角文字で入力し、保存ボタンをクリックする
![都道府県お知らせ一覧のURLに全角文字が入力可能](https://user-images.githubusercontent.com/36686492/81283333-6a884b80-9097-11ea-90cf-2713c099cd46.jpg)

**Comment by zhumeisongsong** [comment]
対応完了しました。
![image](https://user-images.githubusercontent.com/18430762/82273850-8a820e00-99b9-11ea-9dca-ae47700a0060.png)
